spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Abcd@123
    url: jdbc:mysql://localhost:3306/myapp
server:
  port: 8081
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

